seznam/euphoria

README.md, euphoria-examples/pom.xml, euphoria-examples/src/main/java/cz/seznam/euphoria/examples/Executors.java, euphoria-examples/src/main/java/cz/seznam/euphoria/examples/wordcount/SimpleWordCount.java, pom.xml
@d-spirov reminded me ... we're missing an examples module; so here it is :)
=> Add euphoria-examples

euphoria-core/src/main/java/cz/seznam/euphoria/core/client/operator/state/ListStorageDescriptor.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/client/operator/state/StorageDescriptor.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/client/operator/state/ValueStorageDescriptor.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/client/triggers/Trigger.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/client/triggers/TriggerContext.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/executor/greduce/GroupReducer.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/executor/greduce/TriggerStorage.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/streaming/windowing/TriggerMergeContextWrapper.java, euphoria-inmem/src/main/java/cz/seznam/euphoria/inmem/ReduceStateByKeyReducer.java
* Resolves an older, outstanding TODO
=> #! Rename StorageDescriptorBase to StorageDescriptor

euphoria-flink/src/main/java/cz/seznam/euphoria/flink/ExecutionEnvironment.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/FlinkExecutor.java
Allows some experimentation; no explicit functionality based object reuse
=> #! [euphoria-flink] Allow enabling object reuse

euphoria-core/src/main/java/cz/seznam/euphoria/core/client/operator/ReduceByKey.java
=> #! Prefer ValueStorage instead of ListStorage for combining RSBK operations

euphoria-flink/src/main/java/cz/seznam/euphoria/flink/ExecutorContext.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/FlinkExecutor.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/batch/BatchFlowTranslator.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/batch/ReduceByKeyTranslator.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/batch/ReduceStateByKeyTranslator.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/batch/UnionTranslator.java
=> #19 [euphoria-flink] Avoid extra shuffle (on the batch executor)

euphoria-flink/src/main/java/cz/seznam/euphoria/flink/streaming/windowing/AbstractWindowOperator.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/streaming/windowing/MergingWindowSet.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/WindowingTest.java
=> State consistency

euphoria-examples/src/main/java/cz/seznam/euphoria/examples/wordcount/AccessLogCount.java
Working example of simple Apache log aggregation.
=> #! [euphoria-examples] Example of web server log aggregation

euphoria-flink/src/test/java/cz/seznam/euphoria/flink/streaming/RBKTimeWindowTest.java
It seems we're handling late-coming records correctly. `Allowed lateness` is intended to be applied when extracting `event time` from elements. It is not necessary to handle out-of-order elements (late-comers) in case of `ingestion time` since this time characteristics is by definition increasing.
I just added unit test covering the case with out-of-order elements to make sure we're handling this situation correctly.
closes #61
=> #61 Allowed lateness unit test

euphoria-core/src/main/java/cz/seznam/euphoria/core/client/triggers/AfterFirstCompositeTrigger.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/client/triggers/CountTrigger.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/client/triggers/NoopTrigger.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/client/triggers/PeriodicTimeTrigger.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/client/triggers/TimeTrigger.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/client/triggers/Trigger.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/executor/greduce/GroupReducer.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/streaming/windowing/AbstractWindowOperator.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/streaming/windowing/AttachedWindowing.java, euphoria-inmem/src/main/java/cz/seznam/euphoria/inmem/ReduceStateByKeyReducer.java, euphoria-inmem/src/test/java/cz/seznam/euphoria/inmem/InMemExecutorTest.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/ReduceByKeyTest.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/WindowingTest.java
=> #79 [euphoria-core] Trigger#onMerge does not return TriggerResult

pom.xml
=> #85 Move findbugs plugin execution to the process-classes phase

euphoria-core/src/main/java/cz/seznam/euphoria/core/client/dataset/windowing/Count.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/client/dataset/windowing/GlobalWindowing.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/client/dataset/windowing/Windowing.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/executor/FlowValidator.java, euphoria-core/src/test/java/cz/seznam/euphoria/core/client/dataset/windowing/WindowingTest.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/ExecutionEnvironment.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/batch/io/DataSourceWrapper.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/streaming/io/DataSourceWrapper.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/streaming/windowing/AttachedWindowing.java, euphoria-inmem/src/main/java/cz/seznam/euphoria/inmem/InMemExecutor.java, euphoria-inmem/src/test/java/cz/seznam/euphoria/inmem/InMemExecutorTest.java, euphoria-inmem/src/test/java/cz/seznam/euphoria/inmem/JoinOperatorTest.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/JoinWindowEnforcementTest.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/InputTranslator.java
=> #95 Rename Batch to GlobalWindowing

benchmarks/euphoria/euphoria-flink/conf/benchmarks.conf, benchmarks/euphoria/euphoria-flink/src/main/java/cz/seznam/euphoria/benchmarks/euphoria/flink/EuphoriaFlinkTrends.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/FlinkExecutor.java
=> #98 [euphoria-flink] Do not allow object re-use

euphoria-examples/src/main/java/cz/seznam/euphoria/examples/wordcount/AccessLogCount.java, euphoria-examples/src/main/java/cz/seznam/euphoria/examples/wordcount/SimpleWordCount.java
=> #! [euphoria-examples] Provide some more explanatory comments

euphoria-core/src/main/java/cz/seznam/euphoria/core/client/functional/ReduceFunctor.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/client/operator/Distinct.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/client/operator/ReduceByKey.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/client/operator/ReduceWindow.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/executor/util/SingleValueContext.java, euphoria-core/src/test/java/cz/seznam/euphoria/core/client/operator/ReduceStateByKeyTest.java, euphoria-core/src/test/java/cz/seznam/euphoria/core/client/operator/ReduceWindowTest.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/batch/ReduceByKeyTranslator.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/ReduceByKeyTest.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/ReduceByKeyTranslator.java
=> #121 allow multiple elements from reduce by key

euphoria-core/src/main/java/cz/seznam/euphoria/core/executor/storage/FsSpillingListStorage.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/executor/storage/SerializerFactory.java, euphoria-core/src/test/java/cz/seznam/euphoria/core/executor/storage/FsSpillingListStorageTest.java, euphoria-core/src/test/java/cz/seznam/euphoria/core/executor/storage/JavaSerializationFactory.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/batch/BatchOperatorTranslator.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/batch/BatchStateStorageProvider.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/batch/FlinkSerializerFactory.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/batch/ReduceStateByKeyTranslator.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/ReduceByKeyTest.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/ReduceStateByKeyTranslator.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/SparkExecutor.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/SparkFlowTranslator.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/SparkSerializerFactory.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/SparkStorageProvider.java
=> #113 Spilling list storage

euphoria-flink/src/test/java/cz/seznam/euphoria/flink/testkit/FlinkExecutorProvider.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/FlatMapTest.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/JoinTest.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/MapElementsTest.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/ReduceByKeyTest.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/ReduceStateByKeyTest.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/accumulators/Counter.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/accumulators/GetSnapshot.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/accumulators/Histogram.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/accumulators/SingleJvmAccumulatorProvider.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/accumulators/SnapshotProvider.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/accumulators/Snapshotable.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/accumulators/Timer.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/junit/AbstractOperatorTest.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/EventTimeAssigningUnaryFunctor.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/FlatMapTranslator.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/FunctionCollectorAsync.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/FunctionCollectorMem.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/LazyAccumulatorProvider.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/ReduceStateByKeyTranslator.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/UnaryFunctorWrapper.java
* introduces an accumulator provider suitable for the operator testkit
* covers usage and support of accumulators through the operator testkit
* resolves #135
=> #135 Operator test kit accumulator validation

euphoria-core/src/main/java/cz/seznam/euphoria/core/client/accumulators/VoidAccumulatorProvider.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/LazyAccumulatorProvider.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/SparkExecutor.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/SparkExecutorContext.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/SparkFlowTranslator.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/accumulators/SparkAccumulator.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/accumulators/SparkAccumulatorFactory.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/accumulators/SparkCounter.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/accumulators/SparkHistogram.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/accumulators/SparkNativeAccumulators.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/accumulators/SparkTimer.java
=> #134 Implemented support for Spark native accumulators

euphoria-spark/src/main/java/cz/seznam/euphoria/spark/FunctionCollectorAsync.java
- It appears that iterators passed to UDFs can access thread local state set earlier during a tasks' execution
- This patch was required to upgrade euphoria 0.4 to spark 2.1 (the bug revealed only in the streaming executor)
=> #! [euphoria-spark] Correctly transfer global state to executed UDFs

euphoria-examples/build.gradle, settings.gradle
=> Add euphoria-examples module to gradle

benchmarks/benchmark-beam-common/src/main/java/cz/seznam/euphoria/benchmarks/beam/Util.java, build.gradle, euphoria-local/src/main/java/cz/seznam/euphoria/executor/local/LocalExecutor.java, euphoria-local/src/main/java/cz/seznam/euphoria/executor/local/ReduceStateByKeyReducer.java, euphoria-local/src/main/java/cz/seznam/euphoria/executor/local/WatermarkEmitStrategy.java, euphoria-local/src/test/java/cz/seznam/euphoria/executor/local/BasicOperatorTest.java
We should increase report level in the near future.
=> Do not ignore spotbugs failures.

build.gradle
=> [euphoria-build] remove unused protobuf plugin

euphoria-core/src/main/java/cz/seznam/euphoria/core/client/operator/ReduceByKey.java, euphoria-core/src/test/java/cz/seznam/euphoria/core/client/operator/ReduceByKeyTest.java
=>  [euphoria-core] bugfix building of RBK with no windowing

euphoria-core/src/main/java/cz/seznam/euphoria/core/client/operator/Filter.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/client/operator/ReduceWindow.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/ReduceWindowTest.java
Optimize ReduceWindow for better parallelization when using attached windowing (where window label is already known in advance).
=> [euphoria-core] Optimize ReduceWindow operator for attached windowing

euphoria-hadoop/build.gradle, euphoria-hadoop/src/main/java/cz/seznam/euphoria/hadoop/HadoopUtils.java, euphoria-hadoop/src/main/java/cz/seznam/euphoria/hadoop/input/HadoopSource.java, euphoria-hadoop/src/main/java/cz/seznam/euphoria/hadoop/input/SequenceFileSource.java
Removed Writable from sequencefiles (values don't have to be writable).
=> Hadoop tuning

euphoria-core/src/test/java/cz/seznam/euphoria/core/client/operator/ReduceWindowTest.java, euphoria-hadoop/src/main/java/cz/seznam/euphoria/hadoop/input/HadoopSplit.java
This should be the correct way to handle serialization in modern Hadoop.
=> [euphoria-hadoop] InputSplit doesn't have to be Writable

euphoria-examples/src/main/java/cz/seznam/euphoria/examples/Utils.java, euphoria-hadoop/src/main/java/cz/seznam/euphoria/hadoop/output/SequenceFileSink.java, euphoria-hadoop/src/test/java/cz/seznam/euphoria/hadoop/output/HadoopSinkTest.java
Breaking  change because constructor of `SequenceFileSink` is now private. Consider to which version of euphoria to put it.
=> [euphoria-hadoop] SequenceFileSink builder

euphoria-core/src/main/java/cz/seznam/euphoria/core/client/operator/JoinHints.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/executor/util/MultiValueContext.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/batch/BatchFlowTranslator.java, euphoria-flink/src/main/java/cz/seznam/euphoria/flink/batch/BroadcastHashJoinTranslator.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/AllOperatorsSuite.java, euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/BroadcastHashJoinTest.java, euphoria-spark/src/main/java/cz/seznam/euphoria/spark/BroadcastHashJoinTranslator.java
PR for https://github.com/seznam/euphoria/issues/260
=> [euphoria-flink] #260 Flink - broadcast hash join

euphoria-core/src/main/java/cz/seznam/euphoria/core/client/dataset/InputDataset.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/client/dataset/OutputDataset.java, euphoria-core/src/main/java/cz/seznam/euphoria/core/client/io/UnboundedDataSource.java, euphoria-hbase/src/test/java/cz/seznam/euphoria/hbase/HBaseSourceTest.java
=> javadoc fixes

euphoria-hadoop/src/main/java/cz/seznam/euphoria/hadoop/output/SequenceFileSink.java, euphoria-hadoop/src/test/java/cz/seznam/euphoria/hadoop/output/HadoopSinkTest.java
I found some solution to the builder problem, so here's an enhancement proposal. It looks more readable, at least to me. :-)
Inspiration taken from: https://blog.jayway.com/2012/02/07/builder-pattern-with-a-twist/
=> SequenceFileSink builder enhancements
